apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - includeSelectors: true
    includeTemplates: false
    pairs:
      app: allure-ui
  - pairs:
      deployment: allure

resources:
  - config
  - deployment.yaml
  - service.yaml
