apiVersion: v1
kind: PersistentVolume
metadata:
  name: allure-pv
spec:
  storageClassName: standard
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /mnt/data/allure
